### ISSUE TITLE
I couldn't understand the configuration of the model. please can someone clarify?

### ISSUE THREAD

**Issue by preethamgali** [alexa/bort#3]
For bort_4_8_768_1024 mdel:
4 = number of attention heads
8 = number of layers
768 = hidden size
1024 = intermediate size

according to the paper:
Architecture   |    <D, A, H, I>              |Parameters (M)
Bort                |<4, 8, 768, 1024>         |56.1

I think in the implementation the hidden size(H) and intermediate size(I) are interchanged. Isn't it?

**Comment by adewynter** [comment]
Hi Preetham,

Good eye! You are correct -- there is a typo on the paper, where the values for `H` and `I` are flipped. We are working on releasing a revised version for it, but at the moment, the correct assignments to `H` and `I` are the ones in this repository, and more specifically, the ones in the [README](https://github.com/alexa/bort/blob/master/README.md). 

To add to that confusion (sorry), if you go over [this](https://github.com/alexa/bort/blob/master/bort/bort.py) file, what GluonNLP calls the "hidden size" is actually known in some other frameworks as the "intermediate size", and (respectively), the "units" are the "hidden size".

We want to make sure that the notation is uniform across frameworks, so the README is the most up-to-date and accurate version of the configuration; on that file we use the standard nomenclature, where the hidden size is the hidden size on other frameworks (and not the units, because _come on that is just confusing_), and same for the intermediate size.

Hope this helps,

-Adrian
